name: .NET Core Desktop

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore MarkdownReader\MarkdownReader\MarkdownReader.csproj

    - name: Build
      run: dotnet build MarkdownReader\MarkdownReader\MarkdownReader.csproj --configuration Release --no-restore

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test MarkdownReader\MarkdownReader.UnitTests\MarkdownReader.UnitTests.csproj
 
    - uses: actions/upload-artifact@v3
      with:
        name: MarkdownReader.zip
        path: 'D:\a\markdown-reader\markdown-reader\MarkdownReader\MarkdownReader\bin\Release\net6.0-windows\'
        
    - uses: actions/download-artifact@v3
      with:
        name: MarkdownReader.zip
        path: MarkdownReader.zip
