name: .NET Core Desktop

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore MarkdownReader\MarkdownReader\MarkdownReader.csproj
      
    - name: Build
      run: dotnet build MarkdownReader\MarkdownReader.UnitTests\MarkdownReader.UnitTests.csproj --configuration Release

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test MarkdownReader\MarkdownReader.UnitTests\MarkdownReader.UnitTests.csproj
      
    - name: Easy Zip Files
      # You may pin to the exact commit or the version.
      # uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
      uses: vimtor/action-zip@v1
      with:
        # Files or directories to zip
        files: MarkdownReader\MarkdownReader\bin\x64\Release\net6.0-windows/
        # Name of output zip file
        dest: MarkdownReader.zip
        # Whether to add subdirectories to simply zip all files to the root
        recursive: false

    - uses: actions/upload-artifact@v3
      with:
        name: MarkdownReader.zip
        path: MarkdownReader\MarkdownReader\bin\x64\Release\net6.0-windows/MarkdownReader.zip
